### ISSUE TITLE
Sharable baseline resources?

### ISSUE THREAD

**Issue by zhaohan-xi** [anonymous15432/GrammarCNN#12]
Hello Dear Author,

This is a good implementation! Nowadays, there're not so many program generation works that make their codes open-sourced. At the same time, I see there are several AST-based baselines used in your publication, but I didn't find their official resources. It would be better if could play with some of them ([Seq2Tree](https://arxiv.org/abs/1601.01280), [SNM](https://arxiv.org/abs/1704.01696), and [ASN](https://arxiv.org/abs/1704.07535)) together with your GrammarCNN. Could I ask which Github resources (official or unofficial) for these AST-based baseline models are you used?

**Comment by zysszy** [comment]
Hello,

Sorry, we only have the implementation of `Seq2Tree` and `SNM`. 
For other baselines, we directly use the reported performance in the paper.

`Seq2Tree` (https://github.com/donglixp/lang2logic).
`SNM` (https://github.com/pcyin/NL2code).

Zeyu

**Comment by zhaohan-xi** [comment]
Got them, thanks for your recommendations!
