### ISSUE TITLE
what the cmd exactly is?

### ISSUE THREAD

**Issue by tangxiangru** [anonymous15432/GrammarCNN#3]
all I need to do is：
`
python3 run.py train test tree
`
`
python3 run.py train test var
`
`
python3 run.py train test func
`
`
python3 run.py test 
`

or instead:
I need to python run.py 3*3=9 times？

**Comment by zysszy** [comment]
all you to do is：
python3 run.py train test tree
python3 run.py train test var
python3 run.py train test func

However, I think using ‘dev’ instead of ‘test’ can be better. 

And in folder predict/
python3 run.py pre

To generate the code.

**Comment by tangxiangru** [comment]
But test-set is larger than dev-set?

**Comment by tangxiangru** [comment]
So it's stupid to use cmd  like `python3 run.py train train tree`
I mean that your README.md seems Misleading although the paper is a great work.

**Comment by zysszy** [comment]
Thanks, I think you are right. I will update my README soon. 
‘test’ is also work for this task~
‘dev’ and ‘test’ both contain 66 cards from dataset Hearthstone.

**Comment by tangxiangru** [comment]
> contain

so if I use test-set, the dev-set is useless?
