### ISSUE TITLE
CNN implemence in code_generate_model.py

### ISSUE THREAD

**Issue by tangxiangru** [anonymous15432/GrammarCNN#4]
I have another question:
I find that in your `code_generate_model.py` 
the tree-based CNN, tree-path CNN, pre-order CNN all call the same function `def my_conv()` in line 119-128?
so what's the difference? （except the input data）

**Comment by zysszy** [comment]
The input data here is the main difference of those CNNs, but not for tree-based CNN. Tree-based CNN calls the function ‘conv2d’ from tensorflow, not ‘my_conv’.

**Comment by tangxiangru** [comment]
> The input data here is the main difference of those CNNs, but not for tree-based CNN. Tree-based CNN calls the function ‘conv2d’ from tensorflow, not ‘my_conv’.


Yes, my misspoke. That exactly calls another question#5.

**Comment by tangxiangru** [comment]
> > The input data here is the main difference of those CNNs, but not for tree-based CNN. Tree-based CNN calls the function ‘conv2d’ from tensorflow, not ‘my_conv’.
Yes, my misspoke. That exactly calls another question#5.
