### ISSUE TITLE
Your code about data preprocessing

### ISSUE THREAD

**Issue by tangxiangru** [anonymous15432/GrammarCNN#5]
I am surprised about the format of your input data which divide in a tree structure.
SO may you provide your code about how to preprocess the data?
I believe it is the most exquisite part in your work, others could draw on the experience of it.

**Comment by tangxiangru** [comment]
And maybe we will be grateful if you share your data preprocessing code and illustrate your obscure input data

**Comment by zysszy** [comment]
I am willing to share the preprocess. 
However, the preprocess contains several different languages and files, it is hard for releasing. 
So, we didn’t provide this code on Github. 
If you want to get the code, please feel free to contact me. 
My email is szy_@pku.edu.cn
Thanks~

**Comment by tangxiangru** [comment]
> I am willing to share the preprocess.
> However, the preprocess contains several different languages and files, it is hard for releasing.
> So, we didn’t provide this code on Github.
> If you want to get the code, please feel free to contact me.
> My email is [szy_@pku.edu.cn](mailto:szy_@pku.edu.cn)
> Thanks~


okay，anyway
thanks so much and Happy Chinese New Year~

**Comment by zysszy** [comment]
Happy Chinese New Year ~~
